### ISSUE TITLE
作者代码中的 replay_buffer 里面的 randint没有问题

### ISSUE THREAD

**Issue by PeiZhangNEU** [IanYangChina/UOF-paper-code#2]
replay_buffer.py
def sample_achieved_goal_random(self, ep):
        goals = [[], []]
        for k_ in range(self.k):
            done = False
            count = 0
            while not done:
                count += 1
                if count > len(ep):
                    break
                ind = R.randint(0, len(ep)-1)   # pytho自带的 random.randint(low,high) 是闭区间！这里没问题
                goal = ep[ind].achieved_goal
 这里作者也用到的是 randint(low,high-1)的格式，想要取到 0-24 的值，因为python自带的 random.randint(low, high) 是闭区间的，所以这里没有问题，
 是不是上个issue里面的问题是作者把 np.random.randint 和 python自带的 random.randint 搞混了呢？
 一个是左闭右开区间，另一个是左闭右闭区间

**Comment by IanYangChina** [comment]
Yes, that could be my thought at the time when I was writing the codes...thanks for raising up the bug! (Sorry my system doesn't support Chinese input method :)...
